/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as P2pRouteImport } from './routes/p2p'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostRouteImport } from './routes/host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as P2pIndexRouteImport } from './routes/p2p.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsPaymentRouteImport } from './routes/settings.payment'
import { Route as SettingsBettingmodeRouteImport } from './routes/settings.bettingmode'
import { Route as RInviteCodeRouteImport } from './routes/r.$inviteCode'
import { Route as P2pApplyRouteImport } from './routes/p2p.apply'
import { Route as MarketsMarketIdRouteImport } from './routes/markets.$marketId'
import { Route as RInviteCodeTableRouteImport } from './routes/r.$inviteCode_.table'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const P2pRoute = P2pRouteImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const P2pIndexRoute = P2pIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => P2pRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBettingmodeRoute = SettingsBettingmodeRouteImport.update({
  id: '/bettingmode',
  path: '/bettingmode',
  getParentRoute: () => SettingsRoute,
} as any)
const RInviteCodeRoute = RInviteCodeRouteImport.update({
  id: '/r/$inviteCode',
  path: '/r/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const P2pApplyRoute = P2pApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => P2pRoute,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const RInviteCodeTableRoute = RInviteCodeTableRouteImport.update({
  id: '/r/$inviteCode_/table',
  path: '/r/$inviteCode/table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/p2p': typeof P2pRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/p2p/apply': typeof P2pApplyRoute
  '/r/$inviteCode': typeof RInviteCodeRoute
  '/settings/bettingmode': typeof SettingsBettingmodeRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/p2p/': typeof P2pIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/r/$inviteCode/table': typeof RInviteCodeTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/p2p/apply': typeof P2pApplyRoute
  '/r/$inviteCode': typeof RInviteCodeRoute
  '/settings/bettingmode': typeof SettingsBettingmodeRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/p2p': typeof P2pIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/r/$inviteCode/table': typeof RInviteCodeTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/p2p': typeof P2pRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/p2p/apply': typeof P2pApplyRoute
  '/r/$inviteCode': typeof RInviteCodeRoute
  '/settings/bettingmode': typeof SettingsBettingmodeRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/p2p/': typeof P2pIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/r/$inviteCode_/table': typeof RInviteCodeTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/login'
    | '/p2p'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/markets/$marketId'
    | '/p2p/apply'
    | '/r/$inviteCode'
    | '/settings/bettingmode'
    | '/settings/payment'
    | '/settings/preferences'
    | '/settings/profile'
    | '/p2p/'
    | '/settings/'
    | '/r/$inviteCode/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/host'
    | '/login'
    | '/register'
    | '/wallet'
    | '/markets/$marketId'
    | '/p2p/apply'
    | '/r/$inviteCode'
    | '/settings/bettingmode'
    | '/settings/payment'
    | '/settings/preferences'
    | '/settings/profile'
    | '/p2p'
    | '/settings'
    | '/r/$inviteCode/table'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/login'
    | '/p2p'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/markets/$marketId'
    | '/p2p/apply'
    | '/r/$inviteCode'
    | '/settings/bettingmode'
    | '/settings/payment'
    | '/settings/preferences'
    | '/settings/profile'
    | '/p2p/'
    | '/settings/'
    | '/r/$inviteCode_/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRoute: typeof HostRoute
  LoginRoute: typeof LoginRoute
  P2pRoute: typeof P2pRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  WalletRoute: typeof WalletRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  RInviteCodeRoute: typeof RInviteCodeRoute
  RInviteCodeTableRoute: typeof RInviteCodeTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2p': {
      id: '/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof P2pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/p2p/': {
      id: '/p2p/'
      path: '/'
      fullPath: '/p2p/'
      preLoaderRoute: typeof P2pIndexRouteImport
      parentRoute: typeof P2pRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/bettingmode': {
      id: '/settings/bettingmode'
      path: '/bettingmode'
      fullPath: '/settings/bettingmode'
      preLoaderRoute: typeof SettingsBettingmodeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/r/$inviteCode': {
      id: '/r/$inviteCode'
      path: '/r/$inviteCode'
      fullPath: '/r/$inviteCode'
      preLoaderRoute: typeof RInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2p/apply': {
      id: '/p2p/apply'
      path: '/apply'
      fullPath: '/p2p/apply'
      preLoaderRoute: typeof P2pApplyRouteImport
      parentRoute: typeof P2pRoute
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$inviteCode_/table': {
      id: '/r/$inviteCode_/table'
      path: '/r/$inviteCode/table'
      fullPath: '/r/$inviteCode/table'
      preLoaderRoute: typeof RInviteCodeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface P2pRouteChildren {
  P2pApplyRoute: typeof P2pApplyRoute
  P2pIndexRoute: typeof P2pIndexRoute
}

const P2pRouteChildren: P2pRouteChildren = {
  P2pApplyRoute: P2pApplyRoute,
  P2pIndexRoute: P2pIndexRoute,
}

const P2pRouteWithChildren = P2pRoute._addFileChildren(P2pRouteChildren)

interface SettingsRouteChildren {
  SettingsBettingmodeRoute: typeof SettingsBettingmodeRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBettingmodeRoute: SettingsBettingmodeRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRoute: HostRoute,
  LoginRoute: LoginRoute,
  P2pRoute: P2pRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  WalletRoute: WalletRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  RInviteCodeRoute: RInviteCodeRoute,
  RInviteCodeTableRoute: RInviteCodeTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
